[package]
name = "cubedemo"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.22.0"
env_logger = "0.11.7"
glam = "0.30.1"
image = "0.25.6"
pollster = "0.4.0"
sdl3 = { version = "0.14.19", features = ["raw-window-handle"] }
wgpu = "24.0.3"
